# Generated by Django 6.0.2 on 2026-02-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='postal_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
